name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add space https://riimaru:$HF_TOKEN@huggingface.co/spaces/riimaru/wastefy-ai-service
          git checkout --orphan temp-deploy
          git add .
          git commit -m "deploy: latest commit"
          git push space temp-deploy:main --force